{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-alertmanager
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: 9093
      protocol: TCP
      name: web
  selector:
    {{- include "wiki-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
{{- end }}
